version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
      timezone: "UTC"
    commit-message:
      prefix: "CT-5900: "
